.TH DVPLAY 1 "2001 June 19"
.UC 4
.SH NAME
dvplay \- Output DV/IEEE1394 from file
.SH SYNOPSIS
.B dvplay
.SH DESCRIPTION
.I dvplay
is part of the DVTS(Digital Video Transport System).
.I dvplay
reads DV data file created by dvsave, and outputs DV/IEEE1394 packets.
.SH OPTIONS
The options are as follows:
.TP
.BI \-v
Show version number of
.SH BUGS
If you find a bug, please send a e-mail to akimichi@sfc.wide.ad.jp.
Thank you very much.
.SH AUTHORS
Copyright (c) 1999-2003 WIDE Project(http://www.wide.ad.jp/).
.br
.I dvplay
was written by Akimichi OGAWA of Keio university, JAPAN.
DVTS home page (http://www.sfc.wide.ad.jp/DVTS/)
.SH SEE ALSO
dvts(1), dvsend(1), dvsave(1), dvplay(1)
